// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQr084cqviVVqTQLboZhQjGszOcMbuGM4',
    appId: '1:76582614565:web:1bacdb7946f0d90c5a71cc',
    messagingSenderId: '76582614565',
    projectId: 'hospitech-16351',
    authDomain: 'hospitech-16351.firebaseapp.com',
    storageBucket: 'hospitech-16351.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7IbFOBlCwSnzJ0A7ONYoOSfiW4OGP_MU',
    appId: '1:76582614565:android:0245f891f6e083c45a71cc',
    messagingSenderId: '76582614565',
    projectId: 'hospitech-16351',
    storageBucket: 'hospitech-16351.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3wKdSPUP_MEAjVwtaafhIoH7P5hJPQNQ',
    appId: '1:76582614565:ios:204165fd13bc93c15a71cc',
    messagingSenderId: '76582614565',
    projectId: 'hospitech-16351',
    storageBucket: 'hospitech-16351.firebasestorage.app',
    iosBundleId: 'com.example.hospiTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3wKdSPUP_MEAjVwtaafhIoH7P5hJPQNQ',
    appId: '1:76582614565:ios:204165fd13bc93c15a71cc',
    messagingSenderId: '76582614565',
    projectId: 'hospitech-16351',
    storageBucket: 'hospitech-16351.firebasestorage.app',
    iosBundleId: 'com.example.hospiTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQr084cqviVVqTQLboZhQjGszOcMbuGM4',
    appId: '1:76582614565:web:b7347ed3e85da95f5a71cc',
    messagingSenderId: '76582614565',
    projectId: 'hospitech-16351',
    authDomain: 'hospitech-16351.firebaseapp.com',
    storageBucket: 'hospitech-16351.firebasestorage.app',
  );
}